### ISSUE TITLE
PCCA Problem (flatten cause error)

### ISSUE THREAD

**Issue by zhanghaomiao** [markovmodel/msmtools#102]
There is a [flatten Problem](https://github.com/markovmodel/msmtools/blob/devel/msmtools/analysis/dense/pcca.py) in the code

```
closed_components_ev_flat = np.array(closed_components_ev).flatten()
closed_components_enum_flat = np.array(closed_components_enum).flatten()
component_indexes = closed_components_enum_flat[np.argsort(closed_components_ev_flat)[::-1]][0:m]
```
when using the `flatten`, there is a problem. 
For example, if the `closed_components_ev` is 
`[np.array([1,1]),np.array([2,3,4])]` the `flatten()` function cannot convert `closed_components_ev` to one dimensional array. 
So, the `np.argsort` will cause a problem.

On my opinion, the `np.hstack` would do this,

```
closed_components_ev_flat = np.hstack(closed_components_ev)
closed_components_enum_flat = np.hstack(closed_components_enum)
```

**Comment by marscher** [comment]
thanks, but the input arguments here are guaranteed to always have the same shape. Or could you provide any input to pcca() which will cause the problem you have just described?

**Comment by zhanghaomiao** [comment]
For example , the code
``` python
import numpy as np
from msmtools.analysis.dense.pcca import pcca
L = np.array([[0,1,1,0,0,0,0],
              [1,0,1,0,0,0,0],
              [1,1,0,0,0,0,0],
              [0,0,0,0,1,1,1],
              [0,0,0,1,0,1,0],
              [0,0,0,1,1,0,1],
              [0,0,0,1,0,1,0]])

transition_matrix = L/np.sum(L, 1).reshape(-1 ,1)
chi = pcca(transition_matrix,2)
print(chi)
``` 
will cause a sort problem 
> /home/haomiao/soft/anaconda3/bin/python3.6 /home/haomiao/code/markov/test/test_pathway.py
Traceback (most recent call last):
  File "/home/haomiao/code/markov/test/test_pathway.py", line 12, in <module>
    chi = pcca(transition_matrix,2)
  File "/home/haomiao/soft/anaconda3/lib/python3.6/site-packages/msmtools/analysis/dense/pcca.py", line 419, in pcca
    component_indexes = closed_components_enum_flat[np.argsort(closed_components_ev_flat)[::-1]][0:m]
  File "/home/haomiao/soft/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 913, in argsort
    return argsort(axis, kind, order)
ValueError: operands could not be broadcast together with shapes (3,) (4,) 

Process finished with exit code 1

but change the `flatten` function to `hstack` will get 
> [[ 0.  1.]
 [ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]] 

which obtain results correctly

**Comment by marscher** [comment]
Thank you for identifying and demonstrating the problem! We will change
that or do you want to submit a pull request for that?

**Comment by zhanghaomiao** [comment]
You're welcome,  you change that is ok. 
By the way, I learned a lot from your code, Thanks!
