### ISSUE TITLE
how the backward_committor is calculated?

### ISSUE THREAD

**Issue by zhanghaomiao** [markovmodel/msmtools#113]
when the `backward_committor` is calculated, you use the adjoint of the generator matrix 

<a href="https://www.codecogs.com/eqnedit.php?latex=$$K&space;=&space;D_{\pi}(P-I)^{T}$$" target="_blank"><img src="https://latex.codecogs.com/gif.latex?$$K&space;=&space;D_{\pi}(P-I)^{T}$$" title="$$K = D_{\pi}(P-I)^{T}$$" /></a>

I Know when the transition probablity matrix is not reversible, the `backward_committor` is not 
`1-forward_committor`, but how `backward_committor` is calculated in this way? I can't find any reference about it.

**Comment by marscher** [comment]
@trendelkampschroer Are these equations taken from some text book or have you derived these yourself?

**Comment by franknoe** [comment]
You can find the equations for a transition matrix in the SI of this paper (copied below):
    http://www.pnas.org/content/106/45/19011

I don't think msmtools uses 1-forward committors to compute the backward committor unless you have a reversible matrix. The expression above is probably used to compute coefficients for the linear solver.
If in doubt, please refer to the line of code.

![image](https://user-images.githubusercontent.com/6495810/45157819-78ab0800-b1e2-11e8-953e-521e45f76fc1.png)

**Comment by zhanghaomiao** [comment]
@franknoe @marscher Thanks, I get it.
