### ISSUE TITLE
msmtools.analysis.dense.pcca._pcca_connected incorrect?

### ISSUE THREAD

**Issue by pckroon** [markovmodel/msmtools#118]
Hi all,

I tried to adapt your spectral PCCA clustering code for my own purposes, and I think I have stumbled across a bug in your code. It concerns this line: https://github.com/markovmodel/msmtools/blob/54dc76dd2113a0e8f3d15d5316abab41402941be/msmtools/analysis/dense/pcca.py#L307
The comment above states that the memberships should be nonnegative (up to numerical errors). However, in my case they really aren't! I get memberships of ~ -0.8. Truth be told, I don't do exactly the same (I'm clustering atoms in molecules), but I still think this is something that should be investigated.

Cheers,
Peter

**Comment by fabian-paul** [comment]
Hi Peter,

currently the algorithm works only if the the input is a normalized transition matrix. If it is not normalized (e.g. if you input a count matrix), the output is no longer guaranteed to be valid a memberships matrix. I would have to dig a bit into the code to see exactly where this assumption was make and how it can be replaced (it probably can).

Can you formulate your problem with a normalized transition matrix to be sure that that's the problem? 

Best,
Fabian

**Comment by pckroon** [comment]
Hi Fabian,

thanks for the rapid reply. I'm going to dump some code and numbers on you :)
As test case I'll try to PCCA cluster a 6 membered ring into 3 clusters.

First the unnormalized case:
```python3
# A cycle of 6 nodes
# Unnormalized adjacency matrix
[[0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 0.]]
# Eigenvectors corresponding to the 3 largest eigenvalues (Note: I make these using scipy.sparse.linalg.eigsh, so they are always real)
[[ 0.40824829 -0.21868556 -0.53433132]
 [ 0.40824829 -0.57208728 -0.07777841]
 [ 0.40824829 -0.35340171  0.45655291]
 [ 0.40824829  0.21868556  0.53433132]
 [ 0.40824829  0.57208728  0.07777841]
 [ 0.40824829  0.35340171 -0.45655291]]
# And the orthonormalized eigenvectors:
[[ 0.23032943 -0.12338012 -0.30146416]
 [ 0.23032943 -0.32276568 -0.04388177]
 [ 0.23032943 -0.19938557  0.2575824 ]
 [ 0.23032943  0.12338012  0.30146416]
 [ 0.23032943  0.32276568  0.04388177]
 [ 0.23032943  0.19938557 -0.2575824 ]]
# Resulting memberships before truncation
[[-0.25728509  0.07633667  0.41127785]
 [ 0.07450481 -0.25509792  0.41092254]
 [ 0.40878431 -0.25509471  0.07663984]
 [ 0.4112739   0.07634309 -0.25728756]
 [ 0.079484    0.40777769 -0.25693225]
 [-0.25479549  0.40777448  0.07735045]]
# Final memberships
[[0.         0.15655127 0.84344873]
 [0.15348293 0.         0.84651707]
 [0.84211778 0.         0.15788222]
 [0.84343636 0.15656364 0.        ]
 [0.16312384 0.83687616 0.        ]
 [0.         0.8405556  0.1594444 ]]

```
And the normalized version:
```python3
# Normalized transition matrix
[[0.  0.5 0.  0.  0.  0.5]
 [0.5 0.  0.5 0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.  0.5 0. ]]
# First 3 eigenvectors. The corresponding eigenvalues are half as large as in the unnormalized case.
[[ 0.40824829 -0.21868556 -0.53433132]
 [ 0.40824829 -0.57208728 -0.07777841]
 [ 0.40824829 -0.35340171  0.45655291]
 [ 0.40824829  0.21868556  0.53433132]
 [ 0.40824829  0.57208728  0.07777841]
 [ 0.40824829  0.35340171 -0.45655291]]
# And after orthonormalization
[[ 0.23032943 -0.12338012 -0.30146416]
 [ 0.23032943 -0.32276568 -0.04388177]
 [ 0.23032943 -0.19938557  0.2575824 ]
 [ 0.23032943  0.12338012  0.30146416]
 [ 0.23032943  0.32276568  0.04388177]
 [ 0.23032943  0.19938557 -0.2575824 ]]
# And finally the memberships before truncation
[[-0.25728509  0.07633667  0.41127785]
 [ 0.07450481 -0.25509792  0.41092254]
 [ 0.40878431 -0.25509471  0.07663984]
 [ 0.4112739   0.07634309 -0.25728756]
 [ 0.079484    0.40777769 -0.25693225]
 [-0.25479549  0.40777448  0.07735045]]
# Final memberships
[[0.         0.15655127 0.84344873]
 [0.15348293 0.         0.84651707]
 [0.84211778 0.         0.15788222]
 [0.84343636 0.15656364 0.        ]
 [0.16312384 0.83687616 0.        ]
 [0.         0.8405556  0.1594444 ]]
```

Or am I doing the normalization wrong?

**Comment by pckroon** [comment]
Also, when normalizing the found memberships differently, a different answer is found (duh).

Consider the following alternative:
```python3
def _pcca_connected(P, n, return_rot=False):
    ...
    memberships = np.dot(evecs[:, :], rot_matrix)
    memberships -= np.min(memberships, axis=1)[:, np.newaxis]
    memberships /= np.sum(memberships, axis=1)[:, np.newaxis]
    return memberships
```
This gives me the following final memberships:
```python3
[[0.3353526  0.         0.6646474 ]
 [0.67087688 0.         0.32912312]
 [0.66720156 0.33279844 0.        ]
 [0.33220734 0.66779266 0.        ]
 [0.         0.66232102 0.33767898]
 [0.         0.33279514 0.66720486]]
```
Instead of
```python3
[[0.16241199 0.         0.83758801]
 [0.85036028 0.         0.14963972]
 [0.84350625 0.15649375 0.        ]
 [0.15668435 0.84331565 0.        ]
 [0.         0.83385657 0.16614343]
 [0.         0.15660404 0.84339596]]
```

I don't know which one should be considered correct though.

**Comment by fabian-paul** [comment]
Strange,... why is this happening?
I don't get any negative values:
```Python
import numpy as np
import msmtools
a=np.array(
[[0.,  0.5, 0.,  0.,  0.,  0.5],
 [0.5, 0.,  0.5, 0.,  0.,  0. ],
 [0.,  0.5, 0.,  0.5, 0.,  0. ],
 [0.,  0.,  0.5, 0.,  0.5, 0. ],
 [0.,  0.,  0.,  0.5, 0.,  0.5],
 [0.5, 0.,  0.,  0.,  0.5, 0. ]])
msmtools.analysis.dense.pcca._pcca_connected(a, 3)
```
```
array([[  2.86244137e-10,   2.15864980e-04,   9.99784135e-01],
       [  1.00000000e+00,   4.66697679e-20,   2.86837597e-11],       
       [  1.12368682e-16,   2.15865295e-04,   9.99784135e-01],
       [  1.00000000e+00,   3.14927027e-10,   3.57000230e-17],
       [  1.12368682e-16,   2.15865295e-04,   9.99784135e-01],
       [  1.00000000e+00,   3.31172737e-20,   2.86836487e-11]])
```
Commenting out the section 
```Python
        memberships = np.maximum(0.0, memberships)
        memberships = np.minimum(1.0, memberships)
        # print "memberships unnormalized: ",memberships
        for i in range(0, np.shape(memberships)[0]):
                memberships[i] /= np.sum(memberships[i])
```
makes no difference.

Are your eigenvectors othonormalized? _opt_soft is quite picky about its input.

**Comment by fabian-paul** [comment]
I almost sure that you wont get any correct solution if the input transition matrix is not normalized. Formally the "correct" solution is the one that maximizes the objective function: https://github.com/markovmodel/msmtools/blob/devel/msmtools/analysis/dense/pcca.py#L173
However evaluating this function for an arbitrary coarse-grained t-matrix (t-matrix + memberships) might be quite technical... 
I believe that doing the operations
```
    memberships -= np.min(memberships, axis=1)[:, np.newaxis]
    memberships /= np.sum(memberships, axis=1)[:, np.newaxis]
```
does not give a optimal PCCA decomposition (in the sense of maximizing the objective function).

**Comment by pckroon** [comment]
I found it, I made a booboo in isolating the code from msmtools... In particular, here:
https://github.com/markovmodel/msmtools/blob/devel/msmtools/analysis/dense/pcca.py#L287
Because `pi` is not, in fact, pi but rather the stationary distribution.
Thanks a lot for your help :)

**Comment by pckroon** [comment]
Some final remarks:
1) In my case I'm guaranteed to have symmetric transition matrices, which makes things easier
2) orthonormalization is the same as dividing by the constant eigenvector
3) If I do `_soft_opt` with the unnormalized case I get negative memberships (as expected). If I then renormalize the memberships as I do here https://github.com/markovmodel/msmtools/issues/118#issuecomment-471593065 *I get exactly the same memberships as when doing `_soft_opt` with the orthonormalized eigenvectors*.

I'm not going to pretend to understand why that is, but I'll happily treat it as functional magic.
Thanks again for helping me nail this down :)
