### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by debanjansen48** [markovmodel/msmtools#126]
i am trying to install it in a windows machine utilizing pip but return following error

C:\Users\HP\bhmm-master> pip install msmtools
Collecting msmtools
Downloading msmtools-1.2.6.tar.gz (603 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.9/603.9 KB 2.9 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting decorator
Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting scipy>=0.11
Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
Collecting numpy>=1.6.0
Using cached numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
Building wheels for collected packages: msmtools
Building wheel for msmtools (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for msmtools (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [155 lines of output]
Appending msmtools.analysis configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.analysis')
Appending msmtools.analysis.dense configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.analysis.dense')
Appending msmtools.analysis.sparse configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.analysis.sparse')
Appending msmtools.dtraj configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.dtraj')
Appending msmtools.estimation.dense.mle configuration to msmtools.estimation.dense
Ignoring attempt to set 'name' (from 'msmtools.estimation.dense' to 'msmtools.estimation.dense.mle')
Appending msmtools.estimation.dense.tmat_sampling configuration to msmtools.estimation.dense
Ignoring attempt to set 'name' (from 'msmtools.estimation.dense' to 'msmtools.estimation.dense.tmat_sampling')
Appending msmtools.estimation.dense configuration to msmtools.estimation
Ignoring attempt to set 'name' (from 'msmtools.estimation' to 'msmtools.estimation.dense')
Appending msmtools.estimation.sparse.mle.newton configuration to msmtools.estimation.sparse.mle
Ignoring attempt to set 'name' (from 'msmtools.estimation.sparse.mle' to 'msmtools.estimation.sparse.mle.newton')
Appending msmtools.estimation.sparse.mle configuration to msmtools.estimation.sparse
Ignoring attempt to set 'name' (from 'msmtools.estimation.sparse' to 'msmtools.estimation.sparse.mle')
Appending msmtools.estimation.sparse configuration to msmtools.estimation
Ignoring attempt to set 'name' (from 'msmtools.estimation' to 'msmtools.estimation.sparse')
Appending msmtools.estimation configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.estimation')
Appending msmtools.flux configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.flux')
Appending msmtools.flux.dense configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.flux.dense')
Appending msmtools.flux.sparse configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.flux.sparse')
Appending msmtools.generation configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.generation')
Appending msmtools.util configuration to msmtools
Ignoring attempt to set 'name' (from 'msmtools' to 'msmtools.util')
Appending msmtools configuration to
Ignoring attempt to set 'name' (from '' to 'msmtools')
running bdist_wheel
running build
running config_cc
INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
INFO: build_src
INFO: building library "rnglib" sources
INFO: building extension "msmtools.estimation.dense.mle.mle_trev" sources
INFO: building extension "msmtools.estimation.dense.mle.mle_trev_given_pi" sources
INFO: building extension "msmtools.estimation.dense.tmat_sampling.sampler_rev" sources
INFO: building extension "msmtools.estimation.dense.tmat_sampling.sampler_revpi" sources
INFO: building extension "msmtools.estimation.sparse.mle.mle_trev" sources
INFO: building extension "msmtools.estimation.sparse.mle.mle_trev_given_pi" sources
INFO: building extension "msmtools.estimation.sparse.mle.newton.objective_sparse" sources
INFO: building extension "msmtools.util.kahandot" sources
INFO: build_src: building npy-pkg config files
running build_py
creating build
creating build\lib.win-amd64-cpython-310
creating build\lib.win-amd64-cpython-310\msmtools
copying msmtools\setup.py -> build\lib.win-amd64-cpython-310\msmtools
copying msmtools_version.py -> build\lib.win-amd64-cpython-310\msmtools
copying msmtools_init_.py -> build\lib.win-amd64-cpython-310\msmtools
creating build\lib.win-amd64-cpython-310\msmtools\analysis
copying msmtools\analysis\api.py -> build\lib.win-amd64-cpython-310\msmtools\analysis
copying msmtools\analysis_init_.py -> build\lib.win-amd64-cpython-310\msmtools\analysis
creating build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\assessment.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\committor.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\correlations.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\decomposition.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\expectations.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\fingerprints.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\hitting_probability.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\mean_first_passage_time.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\pcca.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\sensitivity.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense\stationary_vector.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
copying msmtools\analysis\dense_init_.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\dense
creating build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\assessment.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\committor.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\decomposition.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\expectations.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\fingerprints.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\mean_first_passage_time.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse\stationary_vector.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
copying msmtools\analysis\sparse_init_.py -> build\lib.win-amd64-cpython-310\msmtools\analysis\sparse
creating build\lib.win-amd64-cpython-310\msmtools\dtraj
copying msmtools\dtraj\api.py -> build\lib.win-amd64-cpython-310\msmtools\dtraj
copying msmtools\dtraj_init_.py -> build\lib.win-amd64-cpython-310\msmtools\dtraj
creating build\lib.win-amd64-cpython-310\msmtools\estimation
copying msmtools\estimation\api.py -> build\lib.win-amd64-cpython-310\msmtools\estimation
copying msmtools\estimation\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation
copying msmtools\estimation_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation
creating build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense\bootstrapping.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense\covariance.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense\ratematrix.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense\transition_matrix.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
copying msmtools\estimation\dense_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense
creating build\lib.win-amd64-cpython-310\msmtools\estimation\dense\mle
copying msmtools\estimation\dense\mle\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\mle
copying msmtools\estimation\dense\mle_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\mle
creating build\lib.win-amd64-cpython-310\msmtools\estimation\dense\tmat_sampling
copying msmtools\estimation\dense\tmat_sampling\sampler_nrev.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\tmat_sampling
copying msmtools\estimation\dense\tmat_sampling\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\tmat_sampling
copying msmtools\estimation\dense\tmat_sampling\tmatrix_sampler.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\tmat_sampling
copying msmtools\estimation\dense\tmat_sampling_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\dense\tmat_sampling
creating build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\connectivity.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\count_matrix.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\effective_counts.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\likelihood.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\prior.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse\transition_matrix.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
copying msmtools\estimation\sparse_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse
creating build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle
copying msmtools\estimation\sparse\mle\setup.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle
copying msmtools\estimation\sparse\mle_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle
creating build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
copying msmtools\estimation\sparse\mle\newton\linsolve.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
copying msmtools\estimation\sparse\mle\newton\linsolve_sparse.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
copying msmtools\estimation\sparse\mle\newton\mle_rev.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
copying msmtools\estimation\sparse\mle\newton\objective_dense.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
copying msmtools\estimation\sparse\mle\newton_init_.py -> build\lib.win-amd64-cpython-310\msmtools\estimation\sparse\mle\newton
creating build\lib.win-amd64-cpython-310\msmtools\flux
copying msmtools\flux\api.py -> build\lib.win-amd64-cpython-310\msmtools\flux
copying msmtools\flux\reactive_flux.py -> build\lib.win-amd64-cpython-310\msmtools\flux
copying msmtools\flux_init_.py -> build\lib.win-amd64-cpython-310\msmtools\flux
creating build\lib.win-amd64-cpython-310\msmtools\flux\dense
copying msmtools\flux\dense\tpt.py -> build\lib.win-amd64-cpython-310\msmtools\flux\dense
copying msmtools\flux\dense_init_.py -> build\lib.win-amd64-cpython-310\msmtools\flux\dense
creating build\lib.win-amd64-cpython-310\msmtools\flux\sparse
copying msmtools\flux\sparse\pathways.py -> build\lib.win-amd64-cpython-310\msmtools\flux\sparse
copying msmtools\flux\sparse\tpt.py -> build\lib.win-amd64-cpython-310\msmtools\flux\sparse
copying msmtools\flux\sparse_init_.py -> build\lib.win-amd64-cpython-310\msmtools\flux\sparse
creating build\lib.win-amd64-cpython-310\msmtools\generation
copying msmtools\generation\api.py -> build\lib.win-amd64-cpython-310\msmtools\generation
copying msmtools\generation_init_.py -> build\lib.win-amd64-cpython-310\msmtools\generation
creating build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\annotators.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\birth_death_chain.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\exceptions.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\matrix.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\numeric.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\setup.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\statistics.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util\types.py -> build\lib.win-amd64-cpython-310\msmtools\util
copying msmtools\util_init_.py -> build\lib.win-amd64-cpython-310\msmtools\util
running build_clib
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: customize MSVCCompiler
INFO: customize MSVCCompiler using build_clib
INFO: CCompilerOpt.cc_test_flags[1021] : testing flags (/O2)
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
INFO: CCompilerOpt.cache_flush[817] : write cache to path -> C:\Users\HP\AppData\Local\Temp\pip-install-13nh84aa\msmtools_6f3f62a6157f41588b42d01728fc3ecf\build\temp.win-amd64-cpython-310\ccompiler_opt_cache_clib.py
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for msmtools
Failed to build msmtools
ERROR: Could not build wheels for msmtools, which is required to install pyproject.toml-based projects
PS C:\Users\HP\bhmm-master>

**Comment by clonker** [comment]
You'll have to download MSVC (https://visualstudio.microsoft.com/de/visual-cpp-build-tools/) to install msmtools via pip or go with the conda-distributed build.

**Comment by clonker** [comment]
I assume this is resolved, feel free to reopen otherwise
