### ISSUE TITLE
implement SIGINT/Ctrl-C handler in reversible estimator

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/msmtools#16]
It would be nice if the reversible estimator could be stopped in an Ipython notebook by clicking Kernel->Interrupt. It seems that one needs to implement a handler in the C extension for this to work.

**Comment by marscher** [comment]
writing a signal handler is a no brainer, in case you just want to forcefully terminate the function execution.

**Comment by fabian-paul** [comment]
Ok, then thank you for nothing! ;-)

**Comment by fabian-paul** [comment]
Why can't I assign myself to the issue here on github?

**Comment by marscher** [comment]
good questions.
