### ISSUE TITLE
Consider Python3 compatibility for more impact.

### ISSUE THREAD

**Issue by marscher** [markovmodel/msmtools#17]
It should be easy to achieve with tools like 2to3 etc.

**Comment by franknoe** [comment]
Good idea.

Am 13/07/15 um 18:09 schrieb Martin K. Scherer:

> It should be easy to achieve with tools like 2to3 etc.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/17.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
I like it very much, thanks for looking into it.

**Comment by franknoe** [comment]
Yes, thanks!

Am 14/07/15 um 17:20 schrieb Benjamin Trendelkamp-Schroer:

> I like it very much, thanks for looking into it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/17#issuecomment-121280120.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
done
