### ISSUE TITLE
compilation failure windows

### ISSUE THREAD

**Issue by marscher** [markovmodel/msmtools#32]
c:\users\appveyor\appdata\local\temp\1\pip-dijvuv-build\msmtools\estimation\dense\sample_rev.h(28) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory

**Comment by rmcgibbo** [comment]
No c99 with msvc. If you use the c++ compilers instead, even with c ABI, its much better.

**Comment by franknoe** [comment]
Hmm, gibts vielleicht nicht für den MS VirtualC++ compiler? Ich habe 
keine Ahnung. Im Prinzip ist das mit den bools nicht wichtig, man kann 
auch 1 oder 0 ints zurückgeben.

Am 17/07/15 um 17:23 schrieb Martin K. Scherer:

> c:\users\appveyor\appdata\local\temp\1\pip-dijvuv-build\msmtools\estimation\dense\sample_rev.h(28) 
> : fatal error C1083: Cannot open include file: 'stdbool.h': No such 
> file or directory
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/32.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@rmcgibbo so you're suggesting to compile all c code with c++ compiler on windows?

**Comment by rmcgibbo** [comment]
Yep. I'm not sure exactly how to do it though. Renaming the .c files to .cc
or .cpp might be enough, not sure.

**Comment by franknoe** [comment]
BTW, welcome to msmtools Robert. This is the package I have mentioned at 
our last omnia meeting where we could start collecting low-level algos 
that are useful for both of us. The package name is still preliminary. 
Please have a look and let us know what you think, and if you see 
possibilities for joining forces here.

Am 17/07/15 um 17:32 schrieb Robert T. McGibbon:

> No c99 with msvc. If you use the c++ compilers instead, even with c 
> ABI, its much better.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/32#issuecomment-122313445.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
maybe by adding language='c++' to the extension declaration in setup.py. Renaming the units to have '.cpp' suffix does not solve the problem.
