### ISSUE TITLE
transition matrix sampler tests

### ISSUE THREAD

**Issue by franknoe** [markovmodel/msmtools#35]
None of the transition matrix sampler tests do test whether the right distribution is sampled. At least the 1D and 2D density validations in the paper should be mapped to a test.

A general way of testing a Bayesian model is to fix a transition matrix P, then generate N trajectories of a fixed length from it. Using transition matrix sampling on each of the count matrices, we should find that on average, c% of the simulations lie in the c% confidence interval.

**Comment by trendelkampschroer** [comment]
Fixed by #47
