### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by franknoe** [markovmodel/msmtools#46]
As discussed in the last Omnia meeting. LGPL is a little less permissive than BSD and ensures that people making changes/improvements to our code have to contribute these changes.

Honestly, I have no idea what it means to change the license in a running project. I guess all code from previous versions is still effectively under BSD because BSD is more permissive.

In the current project state I don't think this makes any differences, but might be relevant later and is useful for license compatibility with other Omnia packages.

**Comment by trendelkampschroer** [comment]
LGPL is okay for me. What about GPL or is omnia all LGPL?

**Comment by franknoe** [comment]
Yes LGPL. GLP is too restrictive in my point of view. That would mean 
that pyEMMA would not be useful to companies.

Am 25/08/15 um 16:20 schrieb Benjamin Trendelkamp-Schroer:

> LGPL is okay for me. What about GPL or is omnia all LGPL?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/msmtools/issues/46#issuecomment-134601806.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Okay, I understand.

**Comment by franknoe** [comment]
Done by #52
