### ISSUE TITLE
Improve documention

### ISSUE THREAD

**Issue by franknoe** [markovmodel/msmtools#58]
The msmtools documentation:

```
http://pythonhosted.org/msmtools/
```

Is a naked API documentation. At least it should contain a welcome page with a description what the package does and installation instructions.

**Comment by franknoe** [comment]
This issue should be addressed. There is currently no reason to become interested in msmtools based on this site...

**Comment by marscher** [comment]
done:  http://msmtools.readthedocs.io/en/latest/index.html
