### ISSUE TITLE
util.statistics.confidence_interval fails for constant data

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/msmtools#66]
``` python

import numpy as np
from msmtools.util.statistics import confidence_interval

x = [np.array([[1, -(1.-1e-5)], [1, +(1-1e-7)]])]*100
confidence_interval(x)

```

Fails with index out of bounds error.  @franknoe: Can you have a look at this.

**Comment by franknoe** [comment]
Sure, I will

**Comment by trendelkampschroer** [comment]
@franknoe: Thanks for the quick fix. It looks good to me. 

If we want to compute the credibility interval/percentile of the given data we can think about using np.percentile inside of util.statistics.confidence_interval in the future

``` python

import numpy as np
data = np.random.randn(10000, 2, 2)
alpha = 0.95 # confidence level
pl = (1-alpha)/2
pu = alpha + (1-alpha)/2 
perc = np.percentile(data, (100*pl, 100*pu), axis=0)
l = perc[0]
u = perc[1]

```

**Comment by franknoe** [comment]
Ah, I didn't know this! Sure, I'm all for replacing homegrown solutions by
standartized ones.
