### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by franknoe** [markovmodel/msmtools#99]
Can we cut a msmtools release? It seems we haven't released since October '16, and there are two new useful features since then.

**Comment by marscher** [comment]
uploaded on conda-forge and pypi. Shall I also do it on omnia?

**Comment by franknoe** [comment]
Yes, we need to give people some time to change to Conda forge. Let's say end of the year? 
In PyEMMA maybe we can generate an import warning if the user has a Conda install and the Conda forge channel is not added 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by marscher** [comment]
On 05/17/2017 08:08 AM, Frank Noe wrote:
> 
> 
> Yes, we need to give people some time to change to Conda forge. Let's say end of the year? 
> In PyEMMA maybe we can generate an import warning if the user has a Conda install and the Conda forge channel is not added 
I was also thinking about that. Luckily one can add patches in conda-recipes, so we can easily add this. Probably for all of the omnia packages
all together.
